### ISSUE TITLE
No directory /etc/openxpki/contrib/local

### ISSUE THREAD

**Issue by bezunartea** [openxpki/openxpki-config#20]
On the Readme, in the section **Credentials / Local Users** it says "copy the directory cp -a /etc/openxpki/contrib/local", but there is no directory "local" in your repository or in the original /etc/openxpki directory.

Am I following the wrong instructions, or is this an issue with the instructions? TIA

**Comment by oliwel** [comment]
The local directory is not used in the current community demo configuration so you have to ignore this. 
Please use the mailing list for support: www.openxpki.org/support.html
