### ISSUE TITLE
key_usable : 0 How to check and reconfig?

### ISSUE THREAD

**Issue by achechet** [openxpki/openxpki-config#21]
I have do import and it is succesful

openxpkiadm certificate import --file vault.crt
Starting import
Successfully imported certificate into database:
  Subject:    CN=DataVault
  Issuer:     CN=DataVault
  Identifier: MZCsZtIxZUhDAI5SvDE5FYDeCt0
  Realm:      none

openxpkiadm alias --realm democa --token datasafe --file vault.crt --key vault.crt
Certificate already registered as alias:
  Alias     : vault-1
  Identifier: MZCsZtIxZUhDAI5SvDE5FYDeCt0
  NotBefore : 2021-07-20 12:10:15
  NotAfter  : 2024-07-24 12:10:15

ERROR: certificate already exisits in group
Alias: vault-1

But 
openxpkicli get_token_info --arg alias=vault-1
{
   "key_name" : "/etc/openxpki/local/keys/vault-1.pem",
   "key_secret" : 1,
   "key_store" : "OPENXPKI",
   "key_usable" : 0
}

How to reconfigure? Where I have done mistake?

**Comment by achechet** [comment]
I have checked it again:

sudo openxpkictl restart
[sudo] пароль для alex: 
Starting OpenXPKI Community Edition v3.12.0
OpenXPKI Server is running and accepting requests.
DONE.
alex@debian:~/works/vault$ ls -al
итого 12
drwxr-xr-x 2 alex alex 4096 июл 20 09:54 .
drwxr-xr-x 8 alex alex 4096 июл 20 09:53 ..
-rwxrwxrwx 1 alex alex  622 июл 20 09:48 vault.openssl.cnf
alex@debian:~/works/vault$ openssl req -x509 -new -config vault.openssl.cnf -subj '/CN=DataVault' -days 1100 -keyout vault.key -out vault.crt 
...+.+..+....+.....+......+....+...+...+..+.+..+....+...+.....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*...+..+.+..+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.............+........+....+......+...........+...................+...............+............+.....+....+........+............+.+...+.....+....+..+...............+....+.....+....+.....+.......+....................+...+...+.........+.+.........+...+..+.+................................+.......+......+..+.+..+....+.....+.+..+.+......+...............+...+........+...............+...+....+...+.....+.......+..................+.....+...+.......+...+.....+.........+......+.+.....+...............+......+............+.+.........+......+..+...............+...+....+...+........................+...+........+...+....+...+..............+....+.........+.....+.+.....+.+.........+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
..........+.+......+.........+.....+...............+.............+..+...+.+..+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*..+...+..+.+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*............+......+........+.+..+.......+......+......+.....+...................+.........+.....................+..+...+....+..+.+..+.+......+.....................+..+......+..........+.....+...................+..+......+...+....+...........+......+.+...+......+........+.......+......+...+.....+..........+.....+......+....+..+...+.+........+................+.....+....+..+....+..+.......+......+.....+.+...+.................................+.........+........+.......+...........+...................+...+..+...+......+.+...+........+.......+......+.....+............+...+.......+.....+..........+...+..+.......+..+....+.....................+........+.......+...+...+.........+........+.+...........+..........+.....+......+..........+...+......+...+........+...+.+......+.....+...+....+...........+.......+...+......+...+...........+.......+............+..+....+......+...+..+...+...+.............+..+..................+...................+..+...+............+....+..+.........+....+...............+.........+.....+.+..............+.............+...+...........+......+..................+....+.......................+...+.......+...+............+........+......+.+.....+.......+...+..+......+.+.....+.+...+.....+..........+..+.........+...+..........+......+..+........................+...+.......+...............+...+..+.....................+............+......+..........+.....+......................+..+...+.......+...+..+......+.+..................+.....+...+...............+..........+..+...+..........+.........+.............................+.......+........+..........+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-----
Warning: No -copy_extensions given; ignoring any extensions in the request

alex@debian:~/works/vault$ ls -al
итого 20
drwxr-xr-x 2 alex alex 4096 июл 20 09:56 .
drwxr-xr-x 8 alex alex 4096 июл 20 09:53 ..
-rwxr-xr-x 1 alex alex 1468 июл 20 09:56 vault.crt
-rwxr-xr-x 1 alex alex 2484 июл 20 09:56 vault.key
-rwxr-xr-x 1 alex alex  622 июл 20 09:48 vault.openssl.cnf
alex@debian:~/works/vault$ sudo openxpkiadm certificate import --file vault.crt
Starting import
Successfully imported certificate into database:
  Subject:    CN=DataVault
  Issuer:     CN=DataVault
  Identifier: _XNiIJXIPNbI5P93Yy7rc94R6aU
  Realm:      none
  
alex@debian:~/works/vault$ sudo openxpkiadm alias --realm democa --token datasafe --file vault.crt --key vault.crt
Certificate already registered as alias:
  Alias     : vault-1
  Identifier: _XNiIJXIPNbI5P93Yy7rc94R6aU
  NotBefore : 2021-07-20 13:56:38
  NotAfter  : 2024-07-24 13:56:38

ERROR: certificate already exisits in group
Alias: vault-1

alex@debian:~/works/vault$ sudo openxpkicli get_token_info --arg alias=vault-1
{
   "key_name" : "/etc/openxpki/local/keys/vault-1.pem",
   "key_secret" : 1,
   "key_store" : "OPENXPKI",
   "key_usable" : 0
}
alex@debian:~/works/vault$

**Comment by oliwel** [comment]
Please use the Mailinglist http://www.openxpki.org/support.html
